/**
 * JOB TRAVELLER PDF — the route sheet that travels with the parts.
 *
 * This is the printed half of the job packet: the same router the MRP export
 * carries, laid out for a human at a machine. It deliberately leaves blank boxes
 * for the operator to write actual time and initials, because that's how a
 * traveller is used on the floor — and those written numbers are what get typed
 * back in as actuals.
 */
import type { JobPacket } from './jobPacket';
import { Page, assemblePdf, wrap, MARGIN, PAGE_W, PAGE_H } from './pdfGenerator';

export function buildJobTravellerPdf(packet: JobPacket): Blob {
  const p = new Page();
  let y = MARGIN;

  // --- Header --------------------------------------------------------------
  p.text(MARGIN, y + 4, packet.source.shopName || 'QuoteForge Machining', 'F2', 18);
  p.textRight(PAGE_W - MARGIN, y + 2, 'JOB TRAVELLER', 'F2', 16);
  y += 26;

  p.text(MARGIN, y, packet.job.jobNumber, 'F2', 22);
  let my = y - 4;
  const metaRight = (label: string, val: string) => {
    p.textRight(PAGE_W - MARGIN - 95, my, label, 'F1', 9);
    p.textRight(PAGE_W - MARGIN, my, val, 'F2', 9);
    my += 13;
  };
  metaRight('Quantity', String(packet.job.quantity));
  if (packet.job.dueDate) metaRight('Due', new Date(packet.job.dueDate).toLocaleDateString());
  if (packet.job.poNumber) metaRight('Customer PO', packet.job.poNumber);
  if (packet.costs.quoteNumber) metaRight('Quote', packet.costs.quoteNumber);

  y = Math.max(y + 18, my) + 6;
  p.line(MARGIN, y, PAGE_W - MARGIN, 1, 0.6);
  y += 18;

  // --- Job facts (two columns) --------------------------------------------
  const colR = PAGE_W / 2 + 10;
  const factRows: Array<[string, string]> = [
    [`Customer: ${packet.customer.name ?? '-'}`, `Part: ${packet.part.name ?? '-'}`],
    [`Material: ${packet.part.material ?? '-'}`, `Stock: ${packet.part.stock ?? '-'}`],
  ];
  for (const [l, r] of factRows) {
    p.text(MARGIN, y, l, 'F1', 10);
    p.text(colR, y, r, 'F1', 10);
    y += 14;
  }
  y += 10;

  // --- Router table --------------------------------------------------------
  const xOp = MARGIN;
  const xName = MARGIN + 34;
  const xWc = MARGIN + 228;
  const xSet = MARGIN + 336;
  const xRun = MARGIN + 386;
  const xPlan = MARGIN + 440;
  const xActual = PAGE_W - MARGIN;

  p.text(xOp, y, 'OP', 'F2', 8);
  p.text(xName, y, 'OPERATION', 'F2', 8);
  p.text(xWc, y, 'WORK CENTRE', 'F2', 8);
  p.textRight(xSet + 26, y, 'SETUP', 'F2', 8);
  p.textRight(xRun + 26, y, 'RUN/PT', 'F2', 8);
  p.textRight(xPlan + 30, y, 'PLANNED', 'F2', 8);
  p.textRight(xActual, y, 'ACTUAL / INITIALS', 'F2', 8);
  y += 5;
  p.line(MARGIN, y, PAGE_W - MARGIN, 0.5, 0.7);
  y += 13;

  const BOTTOM = PAGE_H - MARGIN - 40;
  for (const o of packet.router) {
    if (y > BOTTOM) {
      p.text(MARGIN, y, '… continued (see the exported CSV/JSON for the full router)', 'F1', 8);
      y += 12;
      break;
    }
    p.text(xOp, y, String(o.opNumber), 'F2', 10);
    p.text(xName, y, o.name.slice(0, 40), 'F1', 10);
    p.text(xWc, y, o.workCentreCode.slice(0, 22), 'F1', 9);
    p.textRight(xSet + 26, y, o.setupMin ? `${o.setupMin}m` : '-', 'F1', 9);
    p.textRight(xRun + 26, y, o.runMinPerPart ? `${o.runMinPerPart}m` : '-', 'F1', 9);
    p.textRight(xPlan + 30, y, `${o.totalPlannedMin}m`, 'F1', 9);
    // Blank box for the operator to fill in on the floor.
    p.text(xActual - 96, y, '________________', 'F1', 9);
    y += 12;

    if (o.notes) {
      for (const ln of wrap(o.notes, 92, 2)) {
        p.text(xName, y, ln, 'F1', 7.5);
        y += 9;
      }
    }
    y += 4;
    p.line(MARGIN, y - 2, PAGE_W - MARGIN, 0.25, 0.9);
    y += 4;
  }

  // --- Totals --------------------------------------------------------------
  y += 6;
  p.textRight(xPlan + 30, y, `${packet.totals.plannedTotalMin}m`, 'F2', 10);
  p.text(xName, y, 'Total planned (setup + run × qty)', 'F2', 10);
  y += 20;

  // --- Sign-off ------------------------------------------------------------
  p.line(MARGIN, y, PAGE_W - MARGIN, 0.5, 0.85);
  y += 16;
  p.text(MARGIN, y, 'FINAL INSPECTION', 'F2', 9);
  y += 16;
  p.text(MARGIN, y, 'Qty good ____________     Qty scrap ____________     Inspected by ____________     Date ____________', 'F1', 9);

  p.line(MARGIN, PAGE_H - MARGIN, PAGE_W - MARGIN, 0.5, 0.85);
  p.text(MARGIN, PAGE_H - MARGIN + 14, 'Planned times are estimates — record actuals above.', 'F1', 8);
  p.textRight(PAGE_W - MARGIN, PAGE_H - MARGIN + 14, 'Generated by QuoteForge', 'F1', 8);

  return assemblePdf(p.stream());
}

export function downloadJobTravellerPdf(packet: JobPacket) {
  const blob = buildJobTravellerPdf(packet);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${packet.job.jobNumber}_Traveller.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
